### ISSUE TITLE
Support creation of one BOM from multiple gadgets.

### ISSUE THREAD

**Issue by stevenjswanson** [NVSL/BOMGenerator#10]
Just merge it all together into a single BOM.

**Comment by MichaelMGonzalez** [comment]
The class robots excluding headers, screws, and board materials cost $538.64 according to my tool.

**Comment by MichaelMGonzalez** [comment]
I forgot to make an issue about it, but I implemented CSV generation to test this.
This is the result:
https://docs.google.com/spreadsheets/d/1Ce-vjAGNFOuLwI7kM6KpPZK6S57L7KN5WrDVAbfZ4aQ/edit?usp=sharing
